function JC = jaegerJac(u,h,rhoPP,C)
  k = 2:(length(u)-1);
  JC = diag(-(h(k)+h(k+1)).*(1+0.5.*C.*h(k).*h(k+1).*dydx(u(k),rhoPP,1)))...
       +diag(h(k(1:end-1)),1)...
       +diag(h(k(2:end)),-1);
endfunction
